//product
//create an array in js to store Product details
// A product should contain, name ,price ,discount in %
// calculate discount amount abd after discount and assign to the product itself
//print the product details in following formate:
// Name : ........
//price : Npr .....
//discount: ..............%
//discount Amt : Npr .............
//After Discount : Npr .............

//